x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:1.13.0   # ถอยมาใช้ 1.13.0
    platform: linux/amd64
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    environment:
      - JUDGE0_BYPASS_CGROUP=true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.0
    platform: linux/amd64
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    user: root
    # ท่าไม้ตาย: สร้าง Directory หลอก และ Bypass Cgroup ในระดับ OS
    entrypoint: >
      bash -c "
      mkdir -p /sys/fs/cgroup/memory/box-1 &&
      touch /sys/fs/cgroup/memory/box-1/tasks &&
      mkdir -p /box &&
      chmod 777 /box &&
      export JUDGE0_BYPASS_CGROUP=true &&
      ./scripts/workers"
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
